version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "08:00"
    timezone: Europe/Stockholm
  open-pull-requests-limit: 10
  reviewers:
  - sQVe
  ignore:
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.2
    - 5.1.3
    - 6.0.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.0
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.0
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
  - dependency-name: "@next/eslint-plugin-next"
    versions:
    - 10.0.5
    - 10.0.6
    - 10.0.7
    - 10.0.8
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
  - dependency-name: eslint-config-standard-with-typescript
    versions:
    - 20.0.0
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
  - dependency-name: eslint-plugin-simple-import-sort
    versions:
    - 7.0.0
  - dependency-name: eslint-plugin-standard
    versions:
    - 5.0.0
